const path = require('path');
const Groq = require("groq-sdk");
require("dotenv").config({ path: path.join(__dirname, '..', '.env') });

// Groq connection setup
// API Key automatically picked from process.env.GROQ_API_KEY
const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY 
});

class AIInterviewEngine {
  
  async generateQuestions(cvData, field) {
    // Model: 'llama3-8b-8192' is super fast (Best for Demo)
    const MODEL_NAME = "llama-3.3-70b-versatile";
    
    console.log(`🚀 AI Engine (Groq): Generating mixed questions for '${field}' using ${MODEL_NAME}...`);

    const systemPrompt =  `
    You are a senior technical interviewer conducting a comprehensive hybrid VIDEO and CODING interview.
    Analyze the candidate's Resume and Target Field.
    Generate EXACTLY 5 technical interview questions.
  
    STRICT RULES (CRITICAL):
    1. QUESTION DISTRIBUTION: 
       - Questions 1, 2, and 3 MUST be Verbal/Conceptual questions.
       - Questions 4 and 5 MUST be Technical Coding tasks.
       
    2. VERBAL QUESTIONS (Q1-3): 
       - Test logic, system architecture, and conceptual knowledge. 
       - NEVER ask the candidate to write code for these.
       
    3. CODING QUESTIONS (Q4-5) - SHORT BUT HIGH-SIGNAL (10-15 LINES MAX): 
       - The problem MUST be solvable in 1 to 2 minutes with a maximum of 10 to 15 lines of code.
       - IT MUST NOT BE TRIVIAL. The problem MUST allow the AI to evaluate:
         * Efficiency / Big-O (e.g., using a Hash Map/Set for O(1) lookups vs O(N) nested loops).
         * Best Practices (e.g., handling edge cases, clean variable naming).
         * Problem Solving Logic.
       - Good examples: "Find the first non-repeating character", "Array Intersection", or "Two Sum".
       - Bad examples (Too simple): "Filter even numbers", "Reverse a string using built-in methods".
       - Bad examples (Too long): "Dynamic Programming", "Tree Traversals", "Dijkstra's Algorithm".
  
    REQUIRED JSON OUTPUT FORMAT:
    Return a raw JSON object with a "questions" array. Each object MUST have:
    - "id": Integer (1 to 5)
    - "type": String (Must be exactly "verbal" OR "coding")
    - "question": Short title
    - "description": The detailed problem statement including expected input/output and constraints.
  `;

    // Resume Data ko String mein convert
    const userPrompt = `
      CANDIDATE DATA:
      ${JSON.stringify(cvData)}

      TARGET FIELD:
      ${field}

      STRICT OUTPUT EXAMPLE (MIXED):
      {
        "questions": [
          {
            "id": 1,
            "type": "verbal",
            "question": "API Security",
            "description": "Verbally explain how you would secure a REST API against common attacks like SQL Injection."
          },
          {
            "id": 2,
            "type": "coding",
            "question": "State Management Logic",
            "description": "Given an array of integers and a target, return indices of two numbers that add up to the target.",
            "timeLimitSec": 900
          }
        ]
      }
    `;

    try {
      // 👇 Groq API Call (Instead of Ollama)
      const completion = await groq.chat.completions.create({
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt }
        ],
        model: MODEL_NAME,
        temperature: 0.6,
        // ✨ Critical: Ye ensure karta hai ke Groq valid JSON hi return kare
        response_format: { type: "json_object" } 
      });

      // Groq response structure
      const responseContent = completion.choices[0]?.message?.content;
      
      // JSON Parse karein
      const content = JSON.parse(responseContent || "{}");
      
      console.log("✅ Questions Generated by Groq (Fast!)");
      // Normalize + validate shape (avoid breaking frontend)
      let questions = Array.isArray(content?.questions) ? content.questions : [];
      questions = questions.slice(0, 5).map((q, idx) => ({
        id: Number(q?.id) || idx + 1,
        type: q?.type === "coding" ? "coding" : "verbal",
        question: String(q?.question || `Question ${idx + 1}`),
        description: String(q?.description || ""),
        timeLimitSec: q?.type === "coding" ? (Number(q?.timeLimitSec) || 900) : null
      }));

      // Enforce: exactly 2 coding + 3 verbal
      const codingIdxs = questions
        .map((q, i) => (q.type === "coding" ? i : -1))
        .filter((i) => i >= 0);

      if (codingIdxs.length !== 2) {
        // default everything to verbal first
        questions = questions.map((q) => ({ ...q, type: "verbal", timeLimitSec: null }));
        // make last 2 coding
        const lastTwo = [3, 4];
        for (const i of lastTwo) {
          if (questions[i]) questions[i] = { ...questions[i], type: "coding", timeLimitSec: 900 };
        }
      }

      return questions; 

    } catch (error) {
      console.error("❌ Groq Generation Failed:", error);
      
      // Fallback: Agar Internet issue ho ya API limit cross ho jaye
      return [
        { 
          id: 1, 
          type: "verbal",
          question: "Introduction", 
          description: "Please introduce yourself and highlight your key technical skills." 
        },
        { 
          id: 2, 
          type: "verbal",
          question: "Project Challenge", 
          description: "Describe the most difficult bug you faced in a recent project and how you solved it." 
        },
        { 
          id: 3, 
          type: "verbal",
          question: `Core Concepts of ${field}`, 
          description: `Can you explain a complex concept in ${field} in simple terms?` 
        },
        { 
          id: 4, 
          type: "coding",
          question: "System Design", 
          description: "Given an array of numbers, return the maximum sum of any contiguous subarray (Kadane's algorithm).",
          timeLimitSec: 900
        },
        { 
          id: 5, 
          type: "coding",
          question: "Learning Adaptability", 
          description: "Write a function that checks if a string is a palindrome (ignore spaces and case).",
          timeLimitSec: 900
        }
      ];
    }
  }
}

module.exports = new AIInterviewEngine();